package dev.allofus.fusioncore;
import android.content.*; import android.net.Uri; import android.os.*; import android.provider.Settings; import android.widget.*; import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.core.content.ContextCompat; import dev.allofus.fusioncore.ui.*;
public class SelectorActivity extends BaseFullscreenActivity {
 private static final int REQUEST=1001; private static final String GAME="com.innersloth.spacemafia"; private String pending;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_selector);((Button)findViewById(R.id.btn_launch)).setOnClickListener(v->launchGame());((Button)findViewById(R.id.btn_mods)).setOnClickListener(v->startActivity(new Intent(this,ModProjectsActivity.class)));((Button)findViewById(R.id.btn_settings)).setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));((Button)findViewById(R.id.btn_logs)).setOnClickListener(v->startActivity(new Intent(this,LogsViewerActivity.class)));}
 private void launchGame(){try{if(getPackageManager().getLaunchIntentForPackage(GAME)==null){Toast.makeText(this,"Among Us is not installed",Toast.LENGTH_LONG).show();return;}maybe(GAME);}catch(Throwable e){Toast.makeText(this,"Launch error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private final ActivityResultLauncher<String[]> perms=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),m->{String p=pending;pending=null;if(p!=null)bootstrap(p);});
 private void maybe(String pkg){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.R&&!Environment.isExternalStorageManager()){pending=pkg;try{Intent i=new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION);i.setData(Uri.parse("package:"+getPackageName()));startActivityForResult(i,REQUEST);}catch(Exception e){startActivityForResult(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION),REQUEST);}return;}bootstrap(pkg);}
 private void bootstrap(String pkg){Intent i=new Intent(this,BootstrapActivity.class);i.putExtra(BootstrapActivity.EXTRA_TARGET_PACKAGE,pkg);i.putExtra(BootstrapActivity.EXTRA_USE_ORIGINAL_LIBUNITY,true);startActivity(i);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQUEST&&pending!=null&&(Build.VERSION.SDK_INT<Build.VERSION_CODES.R||Environment.isExternalStorageManager())){String p=pending;pending=null;bootstrap(p);}}
}
