package dev.allofus.fusioncore.ui;
import android.os.*; import android.text.*; import android.view.*; import android.widget.*; import androidx.annotation.Nullable; import com.google.android.material.button.MaterialButton; import dev.allofus.fusioncore.R; import dev.allofus.fusioncore.ide.SyntaxHighlighter; import java.io.*; import java.nio.charset.StandardCharsets;
public class MiniIDEActivity extends BaseFullscreenActivity {
 private final Handler h=new Handler(Looper.getMainLooper()); private EditText editor; private TextView ro; private String path; private boolean readOnly,highlighting; private StringBuilder content; private int chunk; private static final int CHUNK=50000;
 @Override protected void onCreate(@Nullable Bundle b){super.onCreate(b);setContentView(R.layout.activity_mini_ide);editor=findViewById(R.id.editor);ro=findViewById(R.id.tv_read_only);MaterialButton save=findViewById(R.id.btn_save),prev=findViewById(R.id.btn_prev),next=findViewById(R.id.btn_next);path=getIntent().getStringExtra("file_path");readOnly=getIntent().getBooleanExtra("read_only",false);if(path!=null)load(new File(path));if(readOnly){editor.setEnabled(false);ro.setVisibility(View.VISIBLE);save.setVisibility(View.GONE);}else{save.setOnClickListener(v->save());editor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){} public void onTextChanged(CharSequence s,int a,int b,int c){if(!highlighting&&isCs())schedule();} public void afterTextChanged(Editable e){}});}prev.setOnClickListener(v->showChunk(chunk-1));next.setOnClickListener(v->showChunk(chunk+1));}
 private boolean isCs(){return path!=null&&path.toLowerCase().endsWith(".cs");}
 private void load(File f){try{if(!f.isFile())throw new IOException("File not found");byte[] d;try(FileInputStream in=new FileInputStream(f)){d=in.readAllBytes();}String s=new String(d,StandardCharsets.UTF_8);content=new StringBuilder(s);if(s.length()>CHUNK){showChunk(0);}else{setText(s);}}catch(Exception e){Toast.makeText(this,"Load failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void showChunk(int n){if(content==null)return;int max=Math.max(0,(content.length()-1)/CHUNK);chunk=Math.max(0,Math.min(n,max));int a=chunk*CHUNK,b=Math.min(a+CHUNK,content.length());setText(content.substring(a,b));}
 private void setText(String s){highlighting=true;try{editor.setText(isCs()?SyntaxHighlighter.highlightCs(s):s);editor.setSelection(editor.length());}finally{highlighting=false;}}
 private void schedule(){h.removeCallbacksAndMessages("syntax");h.postAtTime(()->{if(!readOnly&&isCs()){int p=Math.max(0,editor.getSelectionStart());setText(editor.getText().toString());editor.setSelection(Math.min(p,editor.length()));}},"syntax",SystemClock.uptimeMillis()+120);}
 private void save(){if(path==null||readOnly)return;try(FileOutputStream o=new FileOutputStream(path,false)){o.write(editor.getText().toString().getBytes(StandardCharsets.UTF_8));content=new StringBuilder(editor.getText());Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Save failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
