package dev.allofus.fusioncore.ui;
import android.content.*; import android.net.Uri; import android.os.*; import android.view.*; import android.widget.*; import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.NonNull; import androidx.recyclerview.widget.*; import com.google.android.material.button.MaterialButton; import dev.allofus.fusioncore.R; import dev.allofus.fusioncore.mod.*; import java.io.*; import java.util.*; import java.util.zip.*;
public class ModProjectsActivity extends BaseFullscreenActivity {
 private static final String GAME="com.innersloth.spacemafia"; private RecyclerView rv; private ModAdapter adapter; private ModProjectManager manager; private final ModValidator validator=new ModValidator(); private boolean mods=true;
 private final ActivityResultLauncher<String[]> picker=registerForActivityResult(new ActivityResultContracts.OpenDocument(),u->{if(u!=null)importFile(u);});
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_mod_projects);manager=new ModProjectManager(this);rv=findViewById(R.id.recycler_mods);rv.setLayoutManager(new LinearLayoutManager(this));adapter=new ModAdapter();rv.setAdapter(adapter);MaterialButton m=findViewById(R.id.btn_external_mods),p=findViewById(R.id.btn_my_mods),up=findViewById(R.id.btn_upload),cr=findViewById(R.id.btn_create);m.setText("Mods");p.setText("Projects");m.setOnClickListener(v->{mods=true;load();});p.setOnClickListener(v->{mods=false;load();});up.setOnClickListener(v->picker.launch(new String[]{"*/*"}));cr.setOnClickListener(v->createDialog());load();}
 private File pluginDir(){File d=new File(new File(Environment.getExternalStorageDirectory(),"FusionCore/"+GAME),"BepInEx/plugins");d.mkdirs();return d;}
 private void importFile(Uri u){File tmpDir=new File(getCacheDir(),"import_"+System.nanoTime()),tmp=new File(tmpDir,"incoming");try{if(!tmpDir.mkdirs())throw new IOException("temp directory");String n=name(u);if(!validator.isValidFileName(n))throw new IllegalArgumentException("Only DLL, CS and ZIP are accepted");long total=0;try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("cannot open file");byte[] b=new byte[8192];int z;while((z=in.read(b))!=-1){total+=z;if(total>ModValidator.MAX_FILE_SIZE)throw new IllegalArgumentException("File is too large (max 25 MB)");out.write(b,0,z);}}if(n.toLowerCase().endsWith(".zip")){if(!validator.validateAndInspectArchive(tmp))throw new IllegalArgumentException("ZIP failed security/content validation");File ex=new File(tmpDir,"extracted");extract(tmp,ex);int c=copyMods(ex,pluginDir());if(c==0)throw new IllegalArgumentException("ZIP has no valid mod files");}else{if(!validator.validateStandalone(tmp))throw new IllegalArgumentException("File content validation failed");copy(tmp,new File(pluginDir(),safe(n)));}Toast.makeText(this,"Accepted after validation",Toast.LENGTH_LONG).show();load();}catch(Exception e){Toast.makeText(this,"Rejected: "+e.getMessage(),Toast.LENGTH_LONG).show();}finally{del(tmpDir);}}
 private void extract(File zip,File dest)throws Exception{dest.mkdirs();String root=dest.getCanonicalPath();try(ZipFile z=new ZipFile(zip)){Enumeration<? extends ZipEntry> en=z.entries();while(en.hasMoreElements()){ZipEntry e=en.nextElement();if(e.isDirectory())continue;File o=new File(dest,e.getName());String p=o.getCanonicalPath();if(!p.equals(root)&&!p.startsWith(root+File.separator))throw new SecurityException("Unsafe ZIP path");File par=o.getParentFile();if(par!=null)par.mkdirs();try(InputStream in=z.getInputStream(e);FileOutputStream out=new FileOutputStream(o)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);}}}}
 private int copyMods(File d,File dest)throws Exception{int c=0;File[] a=d.listFiles();if(a==null)return 0;for(File f:a)if(f.isDirectory())c+=copyMods(f,dest);else{String n=f.getName().toLowerCase();if(n.endsWith(".dll")&&validator.validateStandalone(f)){copy(f,new File(dest,safe(f.getName())));c++;}else if(n.endsWith(".cs")){copy(f,new File(dest,safe(f.getName())));c++;}}return c;}
 private void createDialog(){View v=getLayoutInflater().inflate(R.layout.dialog_create_mod,null);EditText n=v.findViewById(R.id.et_mod_name),ver=v.findViewById(R.id.et_mod_version),pl=v.findViewById(R.id.et_plugin_name);new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Create New Mod Project").setView(v).setPositiveButton("Create",(d,w)->{String a=n.getText().toString().trim(),b=ver.getText().toString().trim(),c=pl.getText().toString().trim();if(a.isEmpty()||c.isEmpty()){Toast.makeText(this,"Name and Plugin are required",Toast.LENGTH_SHORT).show();return;}manager.createProject(a,b.isEmpty()?"1.0.0":b,c);mods=false;load();}).setNegativeButton("Cancel",null).show();}
 private void load(){List<Item> x=new ArrayList<>();if(mods){File[] a=pluginDir().listFiles();if(a!=null)for(File f:a)if(f.isFile()&&f.getName().toLowerCase().endsWith(".dll")){Item i=new Item();i.name=f.getName();i.mod=true;x.add(i);}}else for(ModProjectManager.ModProject p:manager.getProjects()){Item i=new Item();i.name=p.name;i.version=p.version;i.id=p.id;x.add(i);}adapter.set(x);}
 private String name(Uri u){String n=null;try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i);}}catch(Exception ignored){}return safe(n==null?"import.bin":n);}
 private static String safe(String n){return new File(n==null?"import.bin":n).getName().replaceAll("[^A-Za-z0-9._-]","_");} private static void copy(File a,File b)throws Exception{File p=b.getParentFile();if(p!=null)p.mkdirs();try(FileInputStream in=new FileInputStream(a);FileOutputStream out=new FileOutputStream(b)){byte[] z=new byte[8192];int n;while((n=in.read(z))!=-1)out.write(z,0,n);}} private static void del(File f){if(f==null||!f.exists())return;if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File x:a)del(x);}f.delete();}
 private class ModAdapter extends RecyclerView.Adapter<ModAdapter.VH>{List<Item> list=new ArrayList<>();void set(List<Item>x){list=x;notifyDataSetChanged();}@NonNull public VH onCreateViewHolder(@NonNull ViewGroup p,int t){return new VH(LayoutInflater.from(p.getContext()).inflate(R.layout.item_mod_project,p,false));}public void onBindViewHolder(@NonNull VH h,int pos){Item i=list.get(pos);h.name.setText(i.name+(i.version==null?"":" ("+i.version+")"));h.itemView.setOnClickListener(v->{if(i.mod)Toast.makeText(ModProjectsActivity.this,"Installed mod: "+i.name,Toast.LENGTH_SHORT).show();else{Intent x=new Intent(ModProjectsActivity.this,ModDetailActivity.class);x.putExtra("mod_id",i.id);startActivity(x);}});}public int getItemCount(){return list.size();}class VH extends RecyclerView.ViewHolder{TextView name;VH(View v){super(v);name=v.findViewById(R.id.tv_name);}}}
 private static class Item{String name,version,id;boolean mod;}
}
